name: Weekly Version Check

on:
  schedule:
    # This runs at 00:00 UTC weekly on Sunday
    - cron: '0 0 * * *'

jobs:
  check_versions:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run version manager
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        MONGO_URI: ${{ secrets.MONGO_URI }}
        DB_NAME: ${{ secrets.DB_NAME }}
        COLLECTION_NAME: ${{ secrets.COLLECTION_NAME }}
      run: python sdm_versions_manager/version_manager.py

    - name: Commit and push log files
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add logs/
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update SDM logs" && git push)
